[build]
  publish = "frontend/public"
  command = "echo 'No build needed'"

[[redirects]]
  from = "/api/*"
  to = "https://psf-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://psf-backend.onrender.com/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://psf-backend.onrender.com/blog/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
