services:
  # Backend API
  - type: web
    name: psf-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      # Adicione FIREBASE_SERVICE_ACCOUNT manualmente no dashboard do Render
      # Cole o conteúdo completo do serviceAccountKey.json
