services:
  # Full Stack Application (Backend + Frontend)
  - type: web
    name: problemsolverfoundation
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      # Adicione as seguintes variáveis manualmente no dashboard do Render:
      # FIREBASE_PROJECT_ID
      # FIREBASE_CLIENT_EMAIL
      # FIREBASE_PRIVATE_KEY (lembre-se de manter as quebras de linha)
